sudo: required

language: python
python:
  - "3.6"
  - "3.4"
  - "2.7"
# command to install dependencies
before_script:
  - df -h
  - free -g
  - curl checkip.amazonaws.com

script:
  - python locustfile.py