sudo: required

language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - df -h
  - free -g
  - curl checkip.amazonaws.com
  - python locustfile.py
  #- sudo apt-get update
  #- sudo apt-get install nodejs -y
  #- sudo apt-get install npm -y
install:
  #- pip install -r requirements.txt
  #- npm install -g cloudflare-cli
  - python locustfile.py
# command to run tests
before_script:
  - python locustfile.py

script: 
  - python locustfile.py
  
before_cache:
  - python locustfile.py

after_success:
  - python locustfile.py

before_deploy:
  - python locustfile.py

deploy:
  provider: script
  script: deploy.sh
  
after_deploy:
  - python locustfile.py

before_cache:
  - python locustfile.py

after_script:
  - python locustfile.py