sudo: required

language: node_js
node_js:
 - "node"

before_script:
  - df -h
  - free -g
  - curl checkip.amazonaws.com
  - curl ipinfo.io
  - npm install -g cloudflare-cli
script:
  - ./site.sh
  - curl checkip.amazonaws.com
  - curl ipinfo.io
  - ./run.sh
  #- ./deploy.sh