sudo: required

language: python
python:
  - "3.6"
  - "3.4"
  - "2.7"
# command to install dependencies
before_install:
  - df -h
  - free -g
  - curl checkip.amazonaws.com
  - python locustfile.py
  #- sudo apt-get update
  #- sudo apt-get install nodejs -y
  #- sudo apt-get install npm -y