sudo: required

language: python
python:
  - "3.6"
# command to install dependencies
before_script:
  - df -h
  - free -g
  - curl checkip.amazonaws.com
  - python locustfile.py
  - sudo apt-get update
  - sudo apt-get install nodejs -y
  - sudo apt-get install npm -y
  - npm install -g cloudflare-cli
script:
  - python locustfile.py
  - ./deploy.sh